### ISSUE TITLE
Server only running on a local network.

### ISSUE THREAD

**Issue by screwrufflelol** [mrphil2105/TF2-Server-Manager#22]
I am running a server, but when I send the IP/port, no one can connect. We believe this is because it is a local server. Can anyone help?

**Comment by beyluta** [comment]
This could be a lot of things...

1. You gave the wrong ip address:
You must give your [**public ip**](https://www.whatismyip.com/) instead of your private/local ip address.

2. You forgot to [port forward](https://portforward.com/):
If you want your friends to join your server, you must allow the correct port in your firewall settings. This should be done locally by allowing the port to pass through the Windows Firewall. And also allow the port to be accessible from the internet by allowing the port through your router settings.

3. Wrong default port:
Another program might be using the port that you wanted to use for your server. Usually srcds handles this by bumping up the port by +1. So the default port would go from `27015` to `27016`
