### ISSUE TITLE
An error has occurred while running SteamCMD.

### ISSUE THREAD

**Issue by sidhaktheguy** [mrphil2105/TF2-Server-Manager#6]
![wowowowo](https://user-images.githubusercontent.com/33598762/60630089-8ad7e180-9dc6-11e9-8d6d-63a623d1aed2.PNG)

**Comment by sidhaktheguy** [comment]
help bro
idk what i did wrong

**Comment by KingTootsie** [comment]
Happened to me too. I don't understand either. just randomly fails.

**Comment by Ombrezz** [comment]
Same thing here, when running it the first time, it gets an error somewhere in the downloading process then quits.  Afterward, it will quit as soon as the validation step occurs.  A google search returns nothing useful, only with threads about errors that don't even occur on Valve products.  By the way, if anyone has a solution, please explain it here instead of just saying "Fixed it".

**Comment by Ombrezz** [comment]
I figured it out.  You need about 20GB of storage free since every server needs a copy of Steam (for some reason).  The error should give a specific problem in the future so it's easier to diagnose.
